### ISSUE TITLE
Top nav behaves differently on different pages

### ISSUE THREAD

**Issue by mollieru** [partnerandpartners/alliance-for-youth-action#17]
Browser: Safari for Mac

Issue: The horizontal and vertical spacing of the top nav seems inconsistent on different pages (shorter on the pages w/o sub-page it seems), the horizontal location of the top nav seems to change on different pages, and there are some issues with the text of the sub-nav items running into each other.  

![ckk0i60uvw](https://cloud.githubusercontent.com/assets/3680494/24111745/d16628fa-0d6d-11e7-81c4-552820c70cbe.gif)

**Comment by gregmihalko** [comment]
Fixed in c374e40b9fb7b3a0acdf35258b5b45596f592d03
