### ISSUE TITLE
Footer sign up shouldn't have pop modal

### ISSUE THREAD

**Issue by mollieru** [partnerandpartners/alliance-for-youth-action#18]
Browser: Safari for Mac

Issue:  For the sign up in the footer, the input fields should appear in the footer, instead of creating a popup modal.  

![screen shot 2017-03-20 at 1 08 49 pm](https://cloud.githubusercontent.com/assets/3680494/24111987/8ec5ad9e-0d6e-11e7-8b87-f60e7351c71a.png)

**Comment by gregmihalko** [comment]
@mollieru - The lightbox (or an inline reveal of the fields) would be visually cleaner than to have all of those fields exposed all the time? What do you think?

**Comment by mollieru** [comment]
Checked w Sarah on this -- she said we don't actually need First and Last name, and would like to use the more default way the orgs w big digital campaigns, such as Planned Parenthood, are collecting email sign ups -- just email and Zip: 

![screen shot 2017-03-20 at 7 07 01 pm](https://cloud.githubusercontent.com/assets/3680494/24126130/b2d35aae-0da2-11e7-8dbc-a6e469a41a8a.png)

So w fewer fields we can expose both w/o it taking up too much space.
