### ISSUE TITLE
Updating Home image on backend isn't changing homepage

### ISSUE THREAD

**Issue by HenryKraemer** [partnerandpartners/alliance-for-youth-action#20]
Attempted to update main home page image on back end site, but new image is not replacing old image on front end of site.

![screen shot 2017-03-20 at 3 12 53 pm](https://cloud.githubusercontent.com/assets/26556987/24124194/be0252a4-0d7f-11e7-9083-316884d0aef1.png)

**Comment by gregmihalko** [comment]
@HenryKraemer you should be seeing that on the front-end now! Note: due to the way we've structured the backend and frontend, you won't see changes immediately reflected until changes are published from the dashboard.

**Comment by HenryKraemer** [comment]
Thanks, Greg. So how do we publish from the dashboard? I'm trying to make a few other changes to see if they're updating.

**Comment by HenryKraemer** [comment]
Just the "publish all updates" button?

**Comment by gregmihalko** [comment]
Yep!
