### ISSUE TITLE
Dropdown menus issue

### ISSUE THREAD

**Issue by HenryKraemer** [partnerandpartners/alliance-for-youth-action#22]
Not sure if this is appropriate feedback for this stage, but from desktop browsers, the About Page dropdown bunches up against the Campaigns dropdown when you're on the campaigns page.
![screen shot 2017-03-20 at 3 23 04 pm](https://cloud.githubusercontent.com/assets/26556987/24124509/4c9068d4-0d81-11e7-9bc6-5ca00256138e.png)

**Comment by mollieru** [comment]
Good catch! Closing this as it's also captured in https://github.com/partnerandpartners/alliance-for-youth-action/issues/17
