### ISSUE TITLE
On mobile, some text bleeds off screen

### ISSUE THREAD

**Issue by mollieru** [partnerandpartners/alliance-for-youth-action#24]
I know this falls more into styling, but just wanted to flag that there are a number of places where text flows off screen on mobile.

![esc9ofnopy](https://cloud.githubusercontent.com/assets/3680494/24125295/6553b548-0d9e-11e7-9955-dd032ce7ba3a.gif)
![xxspmvw36i](https://cloud.githubusercontent.com/assets/3680494/24125300/680615b0-0d9e-11e7-8fa1-fde2c0df9d3e.gif)

**Comment by HenryKraemer** [comment]
This is happening as well with the front page tagline for words longer than four letters. 

"Get That Power" is what we're like to go with here, but it would also be nice to be able to have a bit more flexibility than a 4 letter maximum for the tagline on the site. I also recognize it can't be too many letters & still make the design work. Would love some greater flexibility and also some guidance on what's reasonable.

![image1](https://cloud.githubusercontent.com/assets/26556987/24490159/393cec7e-14d6-11e7-95d5-f76f49670332.PNG)
