### ISSUE TITLE
Weird title font issues on About page

### ISSUE THREAD

**Issue by HenryKraemer** [partnerandpartners/alliance-for-youth-action#25]
As far as I can tell, "The greatest hits of Alliance policy wins" should have the same title font as "The Origin Story" but they're clearly different on the front end.

![screen shot 2017-03-20 at 6 00 59 pm](https://cloud.githubusercontent.com/assets/26556987/24128150/37c14fa2-0d97-11e7-90d6-f00cfe10a0bb.png)
![screen shot 2017-03-20 at 5 59 28 pm](https://cloud.githubusercontent.com/assets/26556987/24128152/38e70b06-0d97-11e7-9ac1-6e7e44b001de.png)

**Comment by gregmihalko** [comment]
Closed in cbcad434aca883801d245d5fa547835ff4ed7b75
