### ISSUE TITLE
Images break when added to subsection

### ISSUE THREAD

**Issue by HenryKraemer** [partnerandpartners/alliance-for-youth-action#26]
Tried to add "Local Power" image to policy greatest hits on About page. Comes up as broken image link.
![screen shot 2017-03-20 at 6 07 39 pm](https://cloud.githubusercontent.com/assets/26556987/24128311/48d2f592-0d98-11e7-96d0-cf1460d7e972.png)
![screen shot 2017-03-20 at 6 07 42 pm](https://cloud.githubusercontent.com/assets/26556987/24128312/49f27ea2-0d98-11e7-9c1b-9c77b0383688.png)

**Comment by stephenwinsor** [comment]
This seems to be fixed. Closing for now. If it happens, we can reopen the issue.

Note: It may have had something to do with the public status of the API not propagating from the Flywheel control panel.
