### ISSUE TITLE
Replace "Test Affiliate" with Forward Montana

### ISSUE THREAD

**Issue by HenryKraemer** [partnerandpartners/alliance-for-youth-action#32]
Let us know if you need logo stuff for them.

**Comment by gregmihalko** [comment]
Thanks @HenryKraemer - we're planning on giving you all control over these, but send along the highest resolution file you have for them and we'll see if we can drop it in asap!

**Comment by HenryKraemer** [comment]
Cool, e-mailed it over to you. Lemme know if you need it here instead.

**Comment by gregmihalko** [comment]
Fixed by changing this in the backend
