### ISSUE TITLE
Add fields for logos and links for Youth Organizing Partners and Affiliates

### ISSUE THREAD

**Issue by HenryKraemer** [partnerandpartners/alliance-for-youth-action#33]
On Local Organizing Page, it's currently generating logos / links (theoretically) to Alliance Affiliates. It's totally unclear however, how to feature Alliance Youth Organizing Partners. Where do we put logos & links for our Youth Organizing Partners?

**Comment by gregmihalko** [comment]
Fixed in 4dfe59332787ec34de6e797eca8cb65f719deda4
