### ISSUE TITLE
Design: Photo treatment tweak

### ISSUE THREAD

**Issue by HenryKraemer** [partnerandpartners/alliance-for-youth-action#37]
Hey y'all,

We've got a consensus that at least on the front page, we don't want the color of the photo treatment to be so close to the color of the main text. Can you make it a different shade of blue, please?

Thanks!

**Comment by gregmihalko** [comment]
Yep - changing to a different blue might not differentiate it enough though. And the teal tends to wash everything out using the same filter. We may need to use the bright purple? What do you think?

Any other specific reasons why this is a preference that we could work through? Generally unifying the colors helps with the readability and quiets down the amount of alternating values and visuals someone is experiencing when scrolling down the page, but we're happy to adjust.

![screen shot 2017-03-29 at 1 03 56 pm](https://cloud.githubusercontent.com/assets/3373339/24466853/60128044-1480-11e7-9ad8-edb45615e6bf.png)
![screen shot 2017-03-29 at 1 03 22 pm](https://cloud.githubusercontent.com/assets/3373339/24466854/6013dbba-1480-11e7-997d-1cf41f5a141a.png)

**Comment by SarahStadlerBusFed** [comment]
Hi Greg! What if we tried no treatment on these 4 photos? We think the front page is colorful enough that the photos might look best without any treatment.

**Comment by gregmihalko** [comment]
And just use black and white?

![screen shot 2017-03-29 at 1 44 23 pm](https://cloud.githubusercontent.com/assets/3373339/24468364/f9884de4-1485-11e7-8937-be5f63935739.png)

**Comment by SarahStadlerBusFed** [comment]
can you just try full picture or does that look bad because of the photo filters? If so, we'll get you better photos.

**Comment by HenryKraemer** [comment]
I think you mean full color, right Sarah?

**Comment by SarahStadlerBusFed** [comment]
haha full color, yes. Full picture doesn't make sense, my apologies.

**Comment by gregmihalko** [comment]
Yeah, unfortunately, full color doesn't work well for these particular images because of how different the qualities are for each. If you wanted to upload different full-color photos, go for it and we can toggle the filters to see what looks right. 

(If it helps, we obviously think using the same duotone filter across the site would be differentiating and rad!)

**Comment by SarahStadlerBusFed** [comment]
@HenryKraemer thoughts on that?

**Comment by HenryKraemer** [comment]
I guess I wonder if some version of full color treatment other than duotone would work? Is there an instagram-filter-ish version that might work?

I don't love the duotone; I think it diminishes our vibrancy. But I'm also so far from an expert on these matters that I'm not sure anybody should listen to me.

**Comment by SarahStadlerBusFed** [comment]
Also curious what some sort of overlay would look like, or any sort of non-duotone photo treatment option. This isn't hugely important and can be teased out in the final version, but we'd still love to see some non duo-tone photo treatment options (for the site but also could apply to social media templates and template for email/documents)... Our colorado group got a bunch of cool designed photo treatments last year that combine some shaded duotoning with some text overlay that made it look nicer than just straight up duo-tones: 
![14361352_10155293632753206_3012631162233257688_o](https://cloud.githubusercontent.com/assets/26577197/24469363/0fc2d1a8-1470-11e7-8909-89e9d8ec95b9.jpg)
![13087175_10154845591913206_9021200922700347712_o](https://cloud.githubusercontent.com/assets/26577197/24469364/10b0f39c-1470-11e7-901a-7050d87e2df2.png)
![14680951_10155361036283206_9124181824069669589_o](https://cloud.githubusercontent.com/assets/26577197/24469366/11a5b652-1470-11e7-938f-197e0e044d0b.jpg)
![14706813_10155396239563206_3187485958733716145_o](https://cloud.githubusercontent.com/assets/26577197/24469367/128903da-1470-11e7-81ce-9c0f030a9e0a.png)

**Comment by SarahStadlerBusFed** [comment]
So basically, I think we can go with whatever for the soft launch but we still would really love more photo treatment options for all the other materials that aren't straight up duotones. Happy to talk more through that later! @HenryKraemer does that mesh with what you're thinking as well?

**Comment by gregmihalko** [comment]
Those gradients are cool! The duotones / gradients are energetic, unifying and bold. And since the colors are a strong aspect to the identity, and the images aren't the best resolution and/or coming from all kinds of sources it made sense to us to have some treatment in place.

In addition to the header example, we'll play around with more ways that images can have text overlaid, probably not a ton of open-ended text on image control the website, but in some more discreet areas of the materials, we'll be sure to show you a couple examples. Sound good?

**Comment by mollieru** [comment]
Just catching up -- but fwiw I like the gradients and the combo of the blue text and purple duotone treatment.
