### ISSUE TITLE
Design tweaks on front page

### ISSUE THREAD

**Issue by SarahStadlerBusFed** [partnerandpartners/alliance-for-youth-action#39]
Hi Greg, feel free to ignore this if it's not possible for the soft launch, but we're curious if you can change the top of front page to the main blue color instead of the teal (or at least change the top banner to the blue with the all white logo)? The bottom footer is so much easier to read than the top area and I think that's because of the contrast of that dark blue.

**Comment by gregmihalko** [comment]
Agreed, we love the footer as well. I think we could try something like this? 

![screen shot 2017-03-29 at 1 48 50 pm](https://cloud.githubusercontent.com/assets/3373339/24468529/86d2d8f4-1486-11e7-95e0-c650a6c46966.png)

**Comment by SarahStadlerBusFed** [comment]
great!
