### ISSUE TITLE
Staff page spacing

### ISSUE THREAD

**Issue by SarahStadlerBusFed** [partnerandpartners/alliance-for-youth-action#40]
The spacing on the staff page seems a little janky, specifically the lack of spacing between each staff profile. Also, the board lists are spaced oddly - can we change those sections to be white text on the darker blue or something like that so it stands out a bit more? Totally up to y'all but would love if we could make the spacing highlight these folks a bit more.

**Comment by gregmihalko** [comment]
We're working on implementing this, per #31 with an initial layout that's like:
https://invis.io/DEAOZHRN9#/221690484_About-_Staff_-_Board

**Comment by SarahStadlerBusFed** [comment]
Great! Sorry if I didn't catch that on another thread!

**Comment by gregmihalko** [comment]
Fixed in a0c07ef074ff07f9a9c545c1bdc25e34fc2ce335
