### ISSUE TITLE
Inaccuracies on E Pluribus Awesome Map

### ISSUE THREAD

**Issue by HenryKraemer** [partnerandpartners/alliance-for-youth-action#41]
Should have a dot in Seattle, Washington. Should have two dots in Colorado (Denver & Boulder). Should have dots in Ohio for Columbus, Dayton, and Kent. 

Should not have a dot in the northeast.

**Comment by zachmihalko** [comment]
![map](https://cloud.githubusercontent.com/assets/5776098/24478247/244738a2-14a8-11e7-8794-3f8379e7795e.png)

**Comment by HenryKraemer** [comment]
Thanks! Can you spread the Colorado circles out a tad? I know it's not exactly accurate, but it's pretty weird looking at the moment. 

Thanks!

**Comment by zachmihalko** [comment]
![map](https://cloud.githubusercontent.com/assets/5776098/24478352/8d90d66a-14a8-11e7-8a50-cdf300c19863.png)
