### ISSUE TITLE
line size on home page w/ 90% zoom

### ISSUE THREAD

**Issue by SarahStadlerBusFed** [partnerandpartners/alliance-for-youth-action#42]
My browser is always set to 90% zoom, and the homepage has a glitch in the line size:
<img width="526" alt="screen shot 2017-03-30 at 9 22 15 am" src="https://cloud.githubusercontent.com/assets/26577197/24514853/955abef6-152a-11e7-9c05-c8a44235a3d8.png">

**Comment by gregmihalko** [comment]
Good catch!
