### ISSUE TITLE
different fonts - design

### ISSUE THREAD

**Issue by SarahStadlerBusFed** [partnerandpartners/alliance-for-youth-action#43]
Hi all, 

Quick design question - are these lower case fonts all different?
<img width="487" alt="screen shot 2017-03-30 at 9 25 06 am" src="https://cloud.githubusercontent.com/assets/26577197/24514934/d1ee632c-152a-11e7-9ef1-5631ffc50939.png">

I don't love the "Poppin Campaigns" font as it strikes me as super cartoon-y. Is it possible to have that be the same lower case font as the others?

**Comment by gregmihalko** [comment]
Yeah, we're thinking of using Triade in all caps in most cases but make sure any lower case instances use Libre Franklin

<img width="981" alt="screen shot 2017-03-30 at 12 27 49 pm" src="https://cloud.githubusercontent.com/assets/3373339/24515045/50ee5d8a-1544-11e7-9878-6aaa14311c94.png">

**Comment by mollieru** [comment]
I think that sounds like a good plan @gregmihalko !

**Comment by gregmihalko** [comment]
Fixed in 626975a890fa6ea3c3240e2613864388dd615267
