### ISSUE TITLE
Limit line length

### ISSUE THREAD

**Issue by mollieru** [partnerandpartners/alliance-for-youth-action#45]
I can't remember if I flagged this a while back during a flat design iteration, but let's limit line length to 75% (or maybe 2/3 or 3/4 grid -- whichever makes more sense) so that text isn't running all the way across the screen as such:

![screen shot 2017-03-30 at 10 05 51 am](https://cloud.githubusercontent.com/assets/3680494/24516803/c84e13c0-1530-11e7-8e3c-9b92c5d92fcf.png)

**Comment by gregmihalko** [comment]
Will do!
