### ISSUE TITLE
full color images v duotones

### ISSUE THREAD

**Issue by SarahStadlerBusFed** [partnerandpartners/alliance-for-youth-action#51]
but I sent the site to our full staff and they have really strong feelings about the duotone pictures on the home page. Their feedback explicitly is they "really think the photos are much more powerful when they are not all blue toned — Currently the about us page has reg color photos and like it much better."

Can you at least just send me a quick mockup of that homepage in non-duo toned photos so I can share with them? Also, the staff loves the site, so great work!

**Comment by gregmihalko** [comment]
Yep, we'll add in full color photos and send you a quick mockup

**Comment by SarahStadlerBusFed** [comment]
hi team - any update on the full color mockup? Our team would love to see that!

**Comment by gregmihalko** [comment]
Whoops! Yes! Take a look here: https://invis.io/5TB6GXLYC#/225879122_Home_-_AYA_-Beta- <https://invis.io/5TB6GXLYC#/225879122_Home_-_AYA_-Beta->

**Comment by SarahStadlerBusFed** [comment]
Thanks, Greg! So shockingly, the team likes the full color images better (while still keeping the duotone image on the header). They had a question of if the pictures could duotone when you hover over them. Is that an option? ALSO, totally not a big deal for the beta site. We should keep the pictures full color for the launch and then can play around with other options as we refine. Does that work for y'all? Would better photos on the homepage help with the filter/resolution issue?

**Comment by gregmihalko** [comment]
Sounds good! Yes, duotone on hover might work but it will be really important to get better quality images on the homepage, and preferably all convey similar content (i.e. multiple people doing stuff vs one person, active vs passive, etc)

**Comment by SarahStadlerBusFed** [comment]
Greg - do you want me to pick out different images to try for the homepage? I didn't realize we told you guys to use those exact options. I'm happy to get you some alternative options!

**Comment by gregmihalko** [comment]
That would be great - in the folders that Daniela and Henry provided, I didn't see a ton of options but if you have a different stash of higher-res/better quality images to pull from that would be ideal!

**Comment by SarahStadlerBusFed** [comment]
Ohhh okay - you should definitely feel free to use anything in that folder that looks better - we're definitely not wedded to those 4 images. I'll also look for more high res photos somewhere, but obviously am not confident we have em!
