### ISSUE TITLE
Delete the Alliance for Youth Organizing board list

### ISSUE THREAD

**Issue by SarahStadlerBusFed** [partnerandpartners/alliance-for-youth-action#54]
Can we delete the c3/Organizing board list from the site? I tried to do it on the backend and not sure I have the capabilities. We can't have any real c3 content on this site.

**Comment by gregmihalko** [comment]
Yep, we can remove that block entirely for now. You should also have control at the bottom of the staff/board page 
![screen shot 2017-04-03 at 12 47 09 pm](https://cloud.githubusercontent.com/assets/3373339/24620435/affdddee-186b-11e7-962b-9a7a26cebe49.png)
