### ISSUE TITLE
Trying to upload c4 reports on word press

### ISSUE THREAD

**Issue by SarahStadlerBusFed** [partnerandpartners/alliance-for-youth-action#55]
And it's not showing up with an image. Can you help with this? The reports page listed the c3 annual reports so I deleted those and tried to upload the only c4 report we have but the image isn't showing up.

**Comment by stephenwinsor** [comment]
@SarahStadlerBusFed The images for the PDFs have to be generated manually (by you) and then uploaded in the "Featured Image" field. I know it makes things a little tedious, but WordPress isn't able to generate them for us. I set the image for the 2016 report as an example.
