### ISSUE TITLE
Revisions to footer layout and content

### ISSUE THREAD

**Issue by mollieru** [partnerandpartners/alliance-for-youth-action#58]
Expanding this to issue to encompass a few issues with the footer:
1. Footer contents
2. Layout on desktop
2. Layout on mobile

(1) There are a few things missing and a few things present we don't presently need for launch:

- [x] add 'Jobs' and 'Annual Reports' to the 'About' section in footer
- [x] remove links to 'User Agreement,' 'Terms' and 'Privacy Policy' for launch (since we got nada there)

(2) On desktop, footer layout/grid just feels a little off. The visual grid seems to be willynilly and thus the cleanness of that cool expanded version of the logo feels undercut.  Also, the social shorthands seem confusing -- they're spaced differently from everything else and not sure the two-letter short hand is meaningful to most ppl. I'd prefer standard icons which are more recognizable.

One idea: align the right edge of the sitemap ('Donate') with the edge of the logo bars and then contain the newsletter signup within a block. This isn't beautiful (I just snagged the styling of the 'Origin Story' section) but something along these lines perhaps?

![screen shot 2017-04-04 at 3 25 52 pm](https://cloud.githubusercontent.com/assets/3680494/24674999/8cfab0e8-194b-11e7-8155-171b6330afb2.png)

(3) On mobile, footer layout feels confusing in its ordering and spacing. A few observations:

- Vertical spacing in the sitemap feels too tight (hard to click correct link)
- The logo appears in a weird order -- below the sitemap and above the call to action, which I think should be the top item in themobile footer view. (So it would be, in vertical order:newsletter sign up, logo, sitemap).
- On mobile, the input fields for the newsletter signup should span full width. See examples below.

![img_8278](https://cloud.githubusercontent.com/assets/3680494/24631263/885d01c6-1874-11e7-8ca4-0f24bf9d2f01.PNG)
![img_8279](https://cloud.githubusercontent.com/assets/3680494/24631264/88801cc4-1874-11e7-808d-50cc8681819a.PNG)
![img_8280](https://cloud.githubusercontent.com/assets/3680494/24631290/99846ebc-1874-11e7-98da-512acda265de.PNG)

**Comment by mollieru** [comment]
@greg fyi added some more content to this issue (feel free to pull apart into diff issues if that makes more sense)

**Comment by mollieru** [comment]
@gregmihalko also (sorry!!!) i just realized we don't have instagram and youtube accounts at the moment so we only need twitter and Facebook for launch.

is this something that we can/should update in the Wordpress UI?

**Comment by gregmihalko** [comment]
https://invis.io/5TB6GXLYC#/225879122_Home_-_AYA_-Beta-
