### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by gregmihalko** [partnerandpartners/alliance-for-youth-action#59]
HTTPS is enabled on the Netlify side but it's still not showing up in the browser, do we need to enable it on the backend as well?

**Comment by stephenwinsor** [comment]
To get full HTTPS working:

- [ ] Enable (free!) HTTPS on Flywheel (because that's where the images are hosted)
- [ ] Install the "WordPress Force HTTPS" (or a similar platform) on WordPress once https is working on flywheel
- [ ] Check the box for "Force TLS connections" on the backend of netlify

**Comment by stephenwinsor** [comment]
Done & Done!
