### ISSUE TITLE
[Poppin campaigns] Remove link + hover state from 'Why we vote'

### ISSUE THREAD

**Issue by mollieru** [partnerandpartners/alliance-for-youth-action#65]
Since we're not yet linking anywhere, a few tweaks to the 'Why We Vote' section:

- [x] remove the 'Coming soon' link (which is currently taking us to the top of the page)
- [x] remove all hover state functionality
- [x] Change descriptive text to read: "Pumping up the power of young people in elections. More on this soon!"

**Comment by gregmihalko** [comment]
Unfortunately, all these campaigns are pulled in using the same loop so ideally, we'll need to keep the same structure rather than create an exception. It might be the same amount of work to have some content on that page ready by next monday?

**Comment by mollieru** [comment]
Ah -- what if we just remove the link? 

The other option is to remove the image entirely.  I think the content team is way swamped getting content ready for the rollout ;/

**Comment by gregmihalko** [comment]
Closed in 70a0107

**Comment by mollieru** [comment]
@gregmihalko I think maybe in fixing this y'all removed the link for 'Democracy Done Right' as well?
