### ISSUE TITLE
Consistent page header treatment

### ISSUE THREAD

**Issue by mollieru** [partnerandpartners/alliance-for-youth-action#66]
Seems like some pages are getting a fatty teal bar alongside the page title -- which i think looks rad -- but not all pages are. Any rhyme or reason to it?  I really like the way it looks -- and would love to see this applied atleast to all primary section pages, if not all of 'em.

Has a sweet fatty stroke:
![screen shot 2017-04-04 at 2 48 48 pm](https://cloud.githubusercontent.com/assets/3680494/24673321/db9bd7c8-1945-11e7-955f-4c7ee4b120b0.png)

Wishes it had a sweet fatty stroke:
![screen shot 2017-04-04 at 2 48 28 pm](https://cloud.githubusercontent.com/assets/3680494/24673322/dc411756-1945-11e7-947c-d987c4d5c05d.png)

**Comment by gregmihalko** [comment]
Definitely! We're creating a special class to do this across the site!
