### ISSUE TITLE
Slow image load times

### ISSUE THREAD

**Issue by mollieru** [partnerandpartners/alliance-for-youth-action#69]
Perhaps this is just my internet cnxn but I'm finding that on both mobile and desktop there's often a bit of lag for images to load on the site.  Can you make sure we're not loading up super heavy file sizes?

**Comment by gregmihalko** [comment]
It does look like some of the images are prepped much larger than needed, especially on the staff page. We'll see if we can optimize those but it is something to pay attention to for content that you're uploading from your end.

![screen shot 2017-04-05 at 11 02 54 am](https://cloud.githubusercontent.com/assets/3373339/24712027/b1c2b002-19ef-11e7-92da-2f59dbbf69cc.png)

**Comment by mollieru** [comment]
Good point @gregmihalko ! Do you have guidance for the team an max image size so we can make sure we're reducing before we upload?

**Comment by gregmihalko** [comment]
We updated this, but reopen if you're still having issues!
