### ISSUE TITLE
vibrant blue appears differently in Safari v Chrome

### ISSUE THREAD

**Issue by mollieru** [partnerandpartners/alliance-for-youth-action#70]
This is more of a question than an issue, but anyone else noticing the tint of the primary blue is seeming more purple in Safari as compared with Chrome? I noticed the identity materials use more of this purple blue (which is rad) -- just wondering why its rendering differently in Chrome?  (I inspected and the hex code does appear the same -- maybe it's something on my computer?)

See below -- Safari is the top screen, Chrome is the bottom. 

![screen shot 2017-04-07 at 11 24 54 am](https://cloud.githubusercontent.com/assets/3680494/24807133/13698d08-1b85-11e7-8168-323d53c10dca.png)

**Comment by gregmihalko** [comment]
Hey @mollieru unfortunately, we're entering a single rgb/hex value into our stylesheet so the slight differences in color rendering for each browser/operating system's calibration is out of our control!
