### ISSUE TITLE
Can you fix this spacing issue asap?

### ISSUE THREAD

**Issue by SarahStadlerBusFed** [partnerandpartners/alliance-for-youth-action#75]
We're trying to post some job openings tomorrow and just noticed this spacing issue after I drafted and uploaded the postings!
<img width="599" alt="screen shot 2017-04-17 at 2 45 44 pm" src="https://cloud.githubusercontent.com/assets/26577197/25106167/0cf7cc5a-237d-11e7-8f63-7c240e88e398.png">

**Comment by gregmihalko** [comment]
Closed in 141ffc941308c7657485d884838bb09b3765415a
