### ISSUE TITLE
not urgent - additional color options in posting

### ISSUE THREAD

**Issue by SarahStadlerBusFed** [partnerandpartners/alliance-for-youth-action#77]
Hi guys, 

I'm curious if we can get a few more color options for when posting on the site. For example, these job postings are super long and it becomes pretty difficult to read when everything is in blue. Is there an option to change the background color or change some of the text colors (the teal text or black text as options would be ideal in places). Thanks

https://www.allianceforyouthaction.org/job/development-manager/

**Comment by gregmihalko** [comment]
If this is a desire for ad-hoc styling, feel free to use the WYSIWYG editor within wordpress to highlight and change the color of the text.

<img width="541" alt="screen shot 2017-05-05 at 5 33 33 pm" src="https://cloud.githubusercontent.com/assets/3373339/25765192/bc567c6a-31b9-11e7-9bb5-a9c983c73728.png">
